name: Test SSH Connection

#on: workflow_dispatch # السطر ده بيخليك تشغل التيست بضغطة زرار يدوياً
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # السطر ده بيخليك تشغله يدوياً من الموقع
jobs:
  test_conn:
    runs-on: ubuntu-latest
    steps:
      - name: Try to Ping Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HUSSIEN1 }}
          username: ${{ secrets.HUSSIEN2 }}
          key: ${{ secrets.HUSSIEN3 }}
          port: cloudflared tunnel --url ssh://localhost:22
          script: echo "I can see your laptop! Connection Success ✅"
